project:
  type: website

website:
  title: "Language Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sources.qmd
      - split_graphs.qmd
      - nativity.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



